In [2]:
Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [19]:
import numpy as np

In [24]:
n = int(input('Введите число '))
x = np.arange(0,n)
x[::-1]


Введите число22


array([21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,
        4,  3,  2,  1,  0])

In [ ]:
Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [74]:
n = 50
a = np.diag(np.arange(1,n,10), k=0)
print(a)
b = np.asarray(a)
print('Сумма значений по диагонали: ', np.trace(b))



[[ 1  0  0  0  0]
 [ 0 11  0  0  0]
 [ 0  0 21  0  0]
 [ 0  0  0 31  0]
 [ 0  0  0  0 41]]
Сумма значений по диагонали:  105


In [47]:
Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

SyntaxError: invalid syntax (<ipython-input-47-a2e525d3dfb5>, line 1)

In [39]:
a = np.array([[4,2,1], [1,3,0], [0,5,4]])
b = np.array([4,12,-3])
from numpy import linalg
linalg.solve(a,b)

array([ 0.46666667,  3.84444444, -5.55555556])